imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        thumb_item_owl:
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
        
        heighten_120:
            quality: 75
            filters:
                relative_resize: { heighten: 120, widen: 120 }
                
        heighten_250:
            quality: 75
            filters:
                relative_resize: { heighten: 250, widen: 250 }
                
        heighten_300:
            quality: 75
            filters:
                relative_resize: { heighten: 300, widen: 300 }
                watermark:
                    # Relative path to the watermark file (prepended with "%kernel.root_dir%/")
                    image: Resources/data/watermark.png
                    # Size of the watermark relative to the origin images size
                    size: 0.7
                    # Position: One of topleft,top,topright,left,center,right,bottomleft,bottom,bottomright
                    position: center
        
        heighten_60:
            quality: 75
            filters:
                relative_resize: { heighten: 60, widen: 60 }
parameters:
    locale: en
    #locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
            resources:
                - 'SonataCoreBundle:Form:colorpicker.html.twig'
    cache:  false

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                 date_format: DoctrineExtensions\Query\Mysql\DateFormat

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_js_routing:
    routes_to_expose: [csid_basket_add ,csid_orders ,csid_order_send ,csid_order_view]

braincrafted_bootstrap:
    output_dir:
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig
    

sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        service_provider:
            providers:
                - sonata.media.provider.image
    
            formats:
                small: { width: 150 , quality: 75}
                big:   { width: 500, height: 300, quality: 75}
            
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 75}
                big:   { width: 500 , quality: 75}
        
        logo:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 75}
                big:   { width: 500 , quality: 75}  
        signature:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 75}
                big:   { width: 500 , quality: 75}  
        product:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 75}
                big:   { width: 500 , quality: 75}
        images_produits:
            providers:
                - sonata.media.provider.image
            formats:
                preview:   { width: 100, quality: 100}
                small:     { width: 200, quality: 100}
                large:     { width: 600, quality: 100}
        plaquette_pdf:
            providers:
               - sonata.media.provider.file
            formats: ~
        code_ral_pdf:
            providers:
               - sonata.media.provider.file
            formats: ~
        dossier_zip_image:
            providers:
               - sonata.media.provider.file
            formats: ~
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
    providers:
            file:
               service:    sonata.media.provider.file
               resizer:    false
               filesystem: sonata.media.filesystem.local
               cdn:        sonata.media.cdn.server
               generator:  sonata.media.generator.default
               thumbnail:  sonata.media.thumbnail.format
               allowed_extensions: ['pdf'  ,'zip']
               allowed_mime_types: ['application/pdf' ,'application/zip']