# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     my.user.provider.entity:
        class: AppBundle\Security\OAuthUserProvider
        arguments: [@fos_user.user_manager]
     fos_user.registration.form.type:
        class: La2UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fos_user_registration }
