services:
  admin.categorie:
    arguments:
      - ~
      - MobilierIncendieBundle\Entity\Categorie
      - ~
    class: MobilierIncendieBundle\Admin\CategorieAdmin
    tags:
      -
        group: Mobilier incendie
        label: admin.categories
        manager_type: orm
        name: sonata.admin
  admin.color.produit:
        arguments:
          - ~
          - MobilierIncendieBundle\Entity\ProduitColor
          - ~
        class: MobilierIncendieBundle\Admin\ProduitColorAdmin
        tags:
          -
            group: Mobilier incendie
            label: admin.colors
            manager_type: orm
            name: sonata.admin
  admin.produits:
           arguments:
             - ~
             - MobilierIncendieBundle\Entity\Produits
             - ~
           class: MobilierIncendieBundle\Admin\ProduitsAdmin
           tags:
             -
               group: Mobilier incendie
               label: admin.produits
               manager_type: orm
               name: sonata.admin
  admin.modele:
    arguments:
      - ~
      - MobilierIncendieBundle\Entity\Modele
      - ~
    class: MobilierIncendieBundle\Admin\ModeleAdmin
    tags:
      -
        group: Mobilier incendie
        label: admin.version
        manager_type: orm
        name: sonata.admin

  admin.reduction.produit:
        arguments:
          - ~
          - MobilierIncendieBundle\Entity\Reductions
          - ~
        class: MobilierIncendieBundle\Admin\ReductionsAdmin
        tags:
          -
            group: Mobilier incendie
            label: admin.reductions
            manager_type: orm
            name: sonata.admin
  admin.tarifs_client.produit:
          arguments:
            - ~
            - MobilierIncendieBundle\Entity\TarifClientSpecial
            - ~
          class: MobilierIncendieBundle\Admin\TarifClientSpecialAdmin
          tags:
            -
              group: Mobilier incendie
              label: admin.tarifs_client
              manager_type: orm
              name: sonata.admin
  admin.tarifs_livraison.produit:
            arguments:
              - ~
              - MobilierIncendieBundle\Entity\TarifsLivraison
              - ~
            class: MobilierIncendieBundle\Admin\TarifsLivraisonAdmin
            tags:
              -
                group: Mobilier incendie
                label: admin.tarifs_livraison_qte
                manager_type: orm
                name: sonata.admin
  admin.tarifs_livraison_client.produit:
              arguments:
                - ~
                - MobilierIncendieBundle\Entity\TarifsLivraisonParClient
                - ~
              class: MobilierIncendieBundle\Admin\TarifsLivraisonParClientAdmin
              tags:
                -
                  group: Mobilier incendie
                  label: admin.tarifs_livraison_client
                  manager_type: orm
                  name: sonata.admin
  admin.options.produit:
                arguments:
                  - ~
                  - MobilierIncendieBundle\Entity\Options
                  - ~
                class: MobilierIncendieBundle\Admin\OptionsAdmin
                tags:
                  -
                    group: Mobilier incendie
                    label: admin.options
                    manager_type: orm
                    name: sonata.admin
  admin.questions.produit:
                  arguments:
                    - ~
                    - MobilierIncendieBundle\Entity\Questions
                    - ~
                  class: MobilierIncendieBundle\Admin\QuestionsAdmin
                  tags:
                    -
                      group: Mobilier incendie
                      label: admin.questions
                      manager_type: orm
                      name: sonata.admin
   # PDF
  csid.pdf.commande:
          class: MobilierIncendieBundle\Pdf\Pdf
          arguments:
              - @knp_snappy.pdf
              - @templating
  # Mailer
  csid.mailer.commande:
          class: MobilierIncendieBundle\Mailer\Mailer
          arguments:
              - @mailer
              - @router
              - @templating
              - @csid.pdf.commande